//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMaster
    {
        public long Id { get; set; }
        public string ClientName { get; set; }
        public string CompanyType { get; set; }
        public string FoundationYear { get; set; }
        public string TotalEmployees { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public string ContactName { get; set; }
        public string Designation { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string EmailId { get; set; }
        public string WebSiteUrl { get; set; }
        public int BusinessSegmentId { get; set; }
        public bool IsActive { get; set; }
        public long UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string LogoPath { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
