//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientContact
    {
        public long Id { get; set; }
        public long ClientId { get; set; }
        public int BusinessAreaTypeId { get; set; }
        public string ContactName { get; set; }
        public string Designation { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string EmailId { get; set; }
        public long UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
